services:
  web:
    build:
      context: .        # pasta onde está a pasta docker/ e o Dockerfile
      dockerfile: Dockerfile
    image: php:8.2-fpm-alpine
    container_name: portfolio
    ports:
      - "8888:80"               # mapeia porta host → container
      - "443:443"               # mapeia porta host → container
    volumes:
      - ./:/var/www/html       # código fonte sincronizado
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data